### ISSUE TITLE
WebSocket connection to 'wss://172.16.23.13:3443/?peerName=c4aax95q&roomId=1qvyqdjs' failed: Error during WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by jaciyu** [versatica/mediasoup-demo#25]
WebSocket connection to 'wss://172.16.23.13:3443/?peerName=c4aax95q&roomId=1qvyqdjs' failed: Error during WebSocket handshake: Unexpected response code: 500
what's wrong?

**Comment by ibc** [comment]
Your TLS certificate.

**Comment by jaciyu** [comment]
I have already used my own certificate, websocket still cannot shake hands, where is the setting wrong or?

![qq 20180307091953](https://user-images.githubusercontent.com/8733218/37068392-6cb45850-21e9-11e8-9be6-0f9b47f4e80b.jpg)

![qq 20180307095258](https://user-images.githubusercontent.com/8733218/37069361-01815362-21ee-11e8-9280-0dfaf0e9a88f.jpg)

**Comment by jmillan** [comment]
You'll have to troubleshoot your certificate installation...

For maintainability, I would suggest you to properly name certificate files after checking that they are what they are expected to be: ie: `api.freeyun.org.pem` instead of `2.pem`

As a troubleshooting tip, try to establish the TLS connection within the browser by accessing: `https://api.freeyun.org:3443`. It may give you more detail of the connection error.

This is not an issue with mediasoup. Please use the mailing list for questions in the future.

**Comment by tuenli** [comment]
这个问题没有解决吗？
